### ISSUE TITLE
Upload proguard 4.7

### ISSUE THREAD

**Issue by mosabua** [mcpat/proguard-maven-modules#2]
Could you pull the 4.7 release from https://github.com/wvengen/proguard-maven-modules and upload to the Central Repository. I found out about this by asking on g+ 

https://plus.google.com/u/0/105460375065140382634/posts/gGq2ii7GPxY

since I was planning to try to upload myself otherwise but everything seems ready to go and you seem to have access already.. 

I also created a ticket on the proguard issue tracker and we got the ok to upload..

**Comment by mcpat** [comment]
Done.
The modules should be available on maven-central soon.

Thank you for notifying me!

**Comment by mosabua** [comment]
Awesome.. you rock!
